apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tjrt7065z-nodejs 
  janus-idp.io/tekton: tjrt7065z-nodejs
  backstage.io/kubernetes-id: tjrt7065z-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tjrt7065z-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  